/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: a1f297d8c65337c05dbe531ea2d0e98dbe2f70ac */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_deviceatlas_get_properties, 0, 1, MAY_BE_ARRAY|MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO(0, headers, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_deviceatlas_last_error, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_deviceatlas_last_error_msg, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_FUNCTION(deviceatlas_get_properties);
ZEND_FUNCTION(deviceatlas_last_error);
ZEND_FUNCTION(deviceatlas_last_error_msg);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(deviceatlas_get_properties, arginfo_deviceatlas_get_properties)
	ZEND_FE(deviceatlas_last_error, arginfo_deviceatlas_last_error)
	ZEND_FE(deviceatlas_last_error_msg, arginfo_deviceatlas_last_error_msg)
	ZEND_FE_END
};

static void register_deviceatlas_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("DA_OK", DA_OK, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_INVALID_JSON", DA_INVALID_JSON, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_OVERFLOW", DA_OVERFLOW, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_FORMAT_ERROR", DA_FORMAT_ERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_NOMEM", DA_NOMEM, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_SYS", DA_SYS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_NOTIMPL", DA_NOTIMPL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_NOTFOUND", DA_NOTFOUND, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_NOMORE", DA_NOMORE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_INVALID_COOKIE", DA_INVALID_COOKIE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_INVALID_TYPE", DA_INVALID_TYPE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_INVALID_DATA", DA_INVALID_DATA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_INTERNAL_ERROR", DA_INTERNAL_ERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_LOCAL_JSON", DA_LOCAL_JSON, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_PHP_EMPTY_PATH", DA_PHP_EMPTY_PATH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_PHP_BAD_PATH", DA_PHP_BAD_PATH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("DA_PHP_NO_MEM", DA_PHP_NO_MEM, CONST_PERSISTENT);
}
